[common]
; 使用cookie登录，填写true则忽略账号密码，直接从cookies.txt读取cookie登录
use_cookies=false
; 手机号账号(必填)
username = 17377557315
; 登录密码(必填)
password = Rrssbb2005416.
; 要学习的课程ID列表, 逗号隔开(选填，不需要则留空)
; 课程ID列表（已配置）
course_list = 262175471,262175488
; 视频播放倍速(默认1，最大2)
speed = 1.5
; 同时进行的章节数量
jobs = 4
; 遇到关闭任务点时的行为: retry-重试(默认), continue-继续
notopen_action = retry

[tiku]
; 可选项 :
; 1. TikuYanxi(言溪题库 https://tk.enncy.cn/) - 默认选项，免费
; 2. TikuLike(LIKE知识库 https://www.datam.site/)
; 3. TikuAdapter(开源项目 https://github.com/DokiDoki1103/tikuAdapter)
; 4. AI(需自行寻找兼容openai格式的API Endpoint和Key)
; 5. SiliconFlow(硅基流动AI：https://siliconflow.cn/)
provider=TikuYanxi
; 是否启用大模型连接检查
check_llm_connection=true
; 是否提交答题，填写false表示答完题后不提交而是保存搜到的题目
; 填写true表示达到最低题库覆盖率提交
; 对于需要解锁的章节，你必须要提交章节检测才能继续下一章节的学习
submit=true
; 最低题库覆盖率
cover_rate=0.9
; 搜索多个题目时间隔的时间，单位秒
delay=1.0
; 用于言溪题库的TOKEN（留空则使用默认免费额度）
tokens=
; 判断题对应的选项，不要留有空格，逗号为英文逗号
true_list=正确,对,√,是
false_list=错误,错,×,否,不对,不正确

[notification]
; 通知配置（可选，不需要通知可以保持为空）
provider=ServerChan
url=
