name: 刷课

on:
  push:
    branches: [ main ]
  #是否开始每天8点定时刷课，若要开启请把下面两行注释去掉
  #schedule:
  #  - cron: "0 8 * * *"

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v4

      - name: 设置python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 安装依赖包
        run: |
          pip install -r ./requirements.txt

      - name: Run main.py
        run: python main.py -c config.ini
